[Variables]
; Appearance
height=28
width=120
orient=LEFT

BGColor1=20,20,20,200
BGColor2=10,10,10,200

CircleColor1=160,160,160,200
CircleColor2=255,255,255

TextColor1=255,255,255
TextColor2=220,220,220

TextH1=9
TextH2=7

; Info
Drive1=C
Drive2=D
Drive3=H

MediaPlayer=WMP

DLSpeed=3000000
ULSpeed=1000000

BinMax=1000000000

TimeFormat=%#I:%M %p
DateFormat=%a, %#d %B

wCode=ITXX0067
wUnit=f
